app = "fitki-event"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "./Dockerfile"

[experimental]
  auto_rollback = true

# If you have any custom ENV vars you absolutely need at build-time
# or want to pin NODE_ENV, you can do it here:
#[env]
#  NODE_ENV = "production"

[[services]]
  # Fly will set $PORT at runtime—your code should use process.env.PORT!
  internal_port = 8080  
  protocol      = "tcp"
  processes     = ["app"]

  [services.concurrency]
    type       = "connections"
    soft_limit = 20
    hard_limit = 25

  # Expose HTTP and HTTPS
  [[services.ports]]
    handlers    = ["http"]
    port        = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443

[deploy]
  strategy        = "immediate"


