// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Events struct {
	ID          int64          `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	Date        time.Time      `db:"date" json:"date"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
}

type Users struct {
	ID        int64        `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Username  string       `db:"username" json:"username"`
	TgID      int64        `db:"tg_id" json:"tg_id"`
	EventID   int64        `db:"event_id" json:"event_id"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	N         int32        `db:"n" json:"n"`
}
