// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg *CreateEventParams) (*Events, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*Users, error)
	DeleteEvent(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUsersByIdAndEventId(ctx context.Context, arg *DeleteUsersByIdAndEventIdParams) error
	GetEventByID(ctx context.Context, id int64) (*Events, error)
	GetEvents(ctx context.Context) ([]*Events, error)
	GetLastEvent(ctx context.Context) (*Events, error)
	GetUserByID(ctx context.Context, id int64) (*Users, error)
	GetUserByUsername(ctx context.Context, username string) (*Users, error)
	GetUsersByEventID(ctx context.Context, eventID int64) ([]*Users, error)
	UpdateEvent(ctx context.Context, arg *UpdateEventParams) (*Events, error)
}

var _ Querier = (*Queries)(nil)
